import {
  DarkTheme,
  DefaultTheme,
  type Theme,
} from "expo-router/react-navigation";

export const THEME = {
  light: {
    background: "#ffffff",
    foreground: "#252525",
    card: "#ffffff",
    cardForeground: "#252525",
    popover: "#ffffff",
    popoverForeground: "#252525",
    primary: "#343434",
    primaryForeground: "#fafafa",
    secondary: "#f7f7f7",
    secondaryForeground: "#343434",
    muted: "#f7f7f7",
    mutedForeground: "#8e8e8e",
    accent: "#f7f7f7",
    accentForeground: "#343434",
    destructive: "#e5484d",
    border: "#ebebeb",
    input: "#ebebeb",
    ring: "#b5b5b5",
    radius: "0.625rem",
    chart1: "#dedede",
    chart2: "#8e8e8e",
    chart3: "#6b6b6b",
    chart4: "#575757",
    chart5: "#404040",
    surface: "#f8f8f8",
    code: "#f8f8f8",
  },
  dark: {
    background: "#252525",
    foreground: "#fafafa",
    card: "#343434",
    cardForeground: "#fafafa",
    popover: "#343434",
    popoverForeground: "#fafafa",
    primary: "#ebebeb",
    primaryForeground: "#343434",
    secondary: "#404040",
    secondaryForeground: "#fafafa",
    muted: "#404040",
    mutedForeground: "#b5b5b5",
    accent: "#404040",
    accentForeground: "#fafafa",
    destructive: "#e5484d",
    border: "#ffffff1a",
    input: "#ffffff26",
    ring: "#8e8e8e",
    radius: "0.625rem",
    chart1: "#dedede",
    chart2: "#8e8e8e",
    chart3: "#6b6b6b",
    chart4: "#575757",
    chart5: "#404040",
    surface: "#151515",
    code: "#151515",
  },
};

export const NAV_THEME: Record<"light" | "dark", Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
